config/routes.rb
Bloccit::Application.routes.draw do

  get "posts/index"

  resources :links

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: [:show] # create a route for users#show

  resources :users, only: [:show, :index]
  
  resources :posts, only: [:index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :comments, only: [:create, :destroy]
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
    end
  end
  

  match "about" => 'welcome#about', via: :get

  root to: 'welcome#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :name, :url
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def new
    @link = Link.new
    authorize! :create, @link, message: "You need to be an admin to do that."
  end

  def create 
    @link = Link.new(params[:link])
    authorize! :create, @link, message: "You need to be an admin to do that."
    if @link.save
      flash[:notice] = "Link was saved successfully."
      redirect_to @link
    else
      flash[:error] = "Error creating link. Please try again."
      render :new
    end
  end

  def show
    @link = Link.find(params[:id])
  end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for [link], html: { class: 'form-horizontal' } do |f| %>

  <%= control_group_tag(link.errors[:name]) do %>
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  <% end %>

  <%= control_group_tag(link.errors[:url]) do %>
    <%= f.label :url, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :url %>
    </div>
  <% end %>

  <div class="control-group">
    <div class="controls">
      <%= f.submit "Save", class: 'btn' %>
    </div>
  </div>

<% end %>

app/views/links/edit.html.erb
<h1>Edit Link</h1>
<div class="row">
  <div class="span-4">
    <p>Guidelines for existing links:</p>
    <ul>
      <li>Make sure they have name and url.</li>
    </ul>
  </div>
  <div class="span-8">
    <%= render partial: 'form', locals: { link: @link } %>
  </div>
</div>

app/views/links/index.html.erb
<h1>Links</h1>

<div class="span4">
    <% if can? :create, Link %>
      <%= link_to "New Link", new_link_path, class: 'btn btn-large btn-block' %>
    <% end %>
</div>

app/views/links/new.html.erb
<h1>Create Link</h1>
<div class="row">
  <div class="span-4">
    <p>Guidelines for new links:</p>
    <ul>
      <li>Make sure they have name and url.</li>
    </ul>
  </div>
  <div class="span-8">
    <%= render partial: 'form', locals: { link: @link } %>
  </div>
</div>

app/views/links/show.html.erb
<div class="row">
    
  <div class="span6">
    <p><%= @link.name %></p>
  </div>
      
  <div class="span6">
    <a href="<%= @link.url %>" target="_blank"><%= @link.name %></a>
  </div>
    
</div>